title: International Health Systems Group (IHSG), University of Cambridge
description: Home of the International Health Systems Group (IHSG), Department of Engineering, University of Cambridge
theme: just-the-docs

url: https://ihsgcam.github.io/home

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
